version: "3.7"
services:
  web_flask:
    build:
      context: .
#      args:
#        project_directory: "/projects/"
    ports:
      - "8080:80"
#    volumes:
#      - ".:/tmp"
    links:
      - "db"
    environment:
      TZ: "Asia/Tokyo"
      FLASK_ENV: "development"
    command: "python3 app.py"

  db:
    # for compatibility with mysql 5.6
    image: mariadb:10.3
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "labdb"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "password"
      TZ: "Asia/Tokyo"
