version: "3.7"
services:
  web_flask:
    build:
      context: .
#      args:
#        project_directory: "/projects/"
    ports:
      - "5000:80"
#    volumes:
#      - ".:/projects"
    environment:
      TZ: "Asia/Tokyo"
      FLASK_ENV: "development"
    command: "sleep infinity"

  db:
    # has compatible for mysql 5.6
    image: mariadb:10.3
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "labdb"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "password"
      TZ: "Asia/Tokyo"
